/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedEmptyRouteImport } from './routes/_authed/empty'
import { Route as AuthedHistoryRouteImport } from './routes/_authed/history'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as AuthedRegistrarViajeRouteImport } from './routes/_authed/registrar-viaje'
import { Route as AuthedSetupRouteImport } from './routes/_authed/setup'
import { Route as AuthedTripMobileRouteImport } from './routes/_authed/trip-mobile'
import { Route as AuthedTripTabletRouteImport } from './routes/_authed/trip-tablet'
import { Route as AuthedZonasRouteImport } from './routes/_authed/zonas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedEmptyRoute = AuthedEmptyRouteImport.update({
  id: '/empty',
  path: '/empty',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHistoryRoute = AuthedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRegistrarViajeRoute = AuthedRegistrarViajeRouteImport.update({
  id: '/registrar-viaje',
  path: '/registrar-viaje',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSetupRoute = AuthedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTripMobileRoute = AuthedTripMobileRouteImport.update({
  id: '/trip-mobile',
  path: '/trip-mobile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTripTabletRoute = AuthedTripTabletRouteImport.update({
  id: '/trip-tablet',
  path: '/trip-tablet',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedZonasRoute = AuthedZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/empty': typeof AuthedEmptyRoute
  '/history': typeof AuthedHistoryRoute
  '/home': typeof AuthedHomeRoute
  '/registrar-viaje': typeof AuthedRegistrarViajeRoute
  '/setup': typeof AuthedSetupRoute
  '/trip-mobile': typeof AuthedTripMobileRoute
  '/trip-tablet': typeof AuthedTripTabletRoute
  '/zonas': typeof AuthedZonasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/empty': typeof AuthedEmptyRoute
  '/history': typeof AuthedHistoryRoute
  '/home': typeof AuthedHomeRoute
  '/registrar-viaje': typeof AuthedRegistrarViajeRoute
  '/setup': typeof AuthedSetupRoute
  '/trip-mobile': typeof AuthedTripMobileRoute
  '/trip-tablet': typeof AuthedTripTabletRoute
  '/zonas': typeof AuthedZonasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/bienvenida': typeof BienvenidaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/empty': typeof AuthedEmptyRoute
  '/_authed/history': typeof AuthedHistoryRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/registrar-viaje': typeof AuthedRegistrarViajeRoute
  '/_authed/setup': typeof AuthedSetupRoute
  '/_authed/trip-mobile': typeof AuthedTripMobileRoute
  '/_authed/trip-tablet': typeof AuthedTripTabletRoute
  '/_authed/zonas': typeof AuthedZonasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienvenida'
    | '/faq'
    | '/login'
    | '/register'
    | '/empty'
    | '/history'
    | '/home'
    | '/registrar-viaje'
    | '/setup'
    | '/trip-mobile'
    | '/trip-tablet'
    | '/zonas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenida'
    | '/faq'
    | '/login'
    | '/register'
    | '/empty'
    | '/history'
    | '/home'
    | '/registrar-viaje'
    | '/setup'
    | '/trip-mobile'
    | '/trip-tablet'
    | '/zonas'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/bienvenida'
    | '/faq'
    | '/login'
    | '/register'
    | '/_authed/empty'
    | '/_authed/history'
    | '/_authed/home'
    | '/_authed/registrar-viaje'
    | '/_authed/setup'
    | '/_authed/trip-mobile'
    | '/_authed/trip-tablet'
    | '/_authed/zonas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  BienvenidaRoute: typeof BienvenidaRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/empty': {
      id: '/_authed/empty'
      path: '/empty'
      fullPath: '/empty'
      preLoaderRoute: typeof AuthedEmptyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/history': {
      id: '/_authed/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthedHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/registrar-viaje': {
      id: '/_authed/registrar-viaje'
      path: '/registrar-viaje'
      fullPath: '/registrar-viaje'
      preLoaderRoute: typeof AuthedRegistrarViajeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/setup': {
      id: '/_authed/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthedSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trip-mobile': {
      id: '/_authed/trip-mobile'
      path: '/trip-mobile'
      fullPath: '/trip-mobile'
      preLoaderRoute: typeof AuthedTripMobileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trip-tablet': {
      id: '/_authed/trip-tablet'
      path: '/trip-tablet'
      fullPath: '/trip-tablet'
      preLoaderRoute: typeof AuthedTripTabletRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/zonas': {
      id: '/_authed/zonas'
      path: '/zonas'
      fullPath: '/zonas'
      preLoaderRoute: typeof AuthedZonasRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedEmptyRoute: typeof AuthedEmptyRoute
  AuthedHistoryRoute: typeof AuthedHistoryRoute
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedRegistrarViajeRoute: typeof AuthedRegistrarViajeRoute
  AuthedSetupRoute: typeof AuthedSetupRoute
  AuthedTripMobileRoute: typeof AuthedTripMobileRoute
  AuthedTripTabletRoute: typeof AuthedTripTabletRoute
  AuthedZonasRoute: typeof AuthedZonasRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedEmptyRoute: AuthedEmptyRoute,
  AuthedHistoryRoute: AuthedHistoryRoute,
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedRegistrarViajeRoute: AuthedRegistrarViajeRoute,
  AuthedSetupRoute: AuthedSetupRoute,
  AuthedTripMobileRoute: AuthedTripMobileRoute,
  AuthedTripTabletRoute: AuthedTripTabletRoute,
  AuthedZonasRoute: AuthedZonasRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  BienvenidaRoute: BienvenidaRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
